// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBga9QG0Hn5Ym9SwtwEeH_0JBAQnawSuHM',
    appId: '1:665514511694:web:85855caf50b8721ac3221f',
    messagingSenderId: '665514511694',
    projectId: 'test-6689e',
    authDomain: 'test-6689e.firebaseapp.com',
    storageBucket: 'test-6689e.firebasestorage.app',
    measurementId: 'G-REQ3XBZFP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbKrU7wbYpZq52OozMYIvIjEZQoRlensI',
    appId: '1:665514511694:android:80d45468bcf1cdd8c3221f',
    messagingSenderId: '665514511694',
    projectId: 'test-6689e',
    storageBucket: 'test-6689e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJg0Jy6bs6RzkZEBqsiFKkPpZ0mg43QlE',
    appId: '1:665514511694:ios:39c71f237047a2f3c3221f',
    messagingSenderId: '665514511694',
    projectId: 'test-6689e',
    storageBucket: 'test-6689e.firebasestorage.app',
    iosBundleId: 'com.example.schoolNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJg0Jy6bs6RzkZEBqsiFKkPpZ0mg43QlE',
    appId: '1:665514511694:ios:39c71f237047a2f3c3221f',
    messagingSenderId: '665514511694',
    projectId: 'test-6689e',
    storageBucket: 'test-6689e.firebasestorage.app',
    iosBundleId: 'com.example.schoolNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBga9QG0Hn5Ym9SwtwEeH_0JBAQnawSuHM',
    appId: '1:665514511694:web:8b4581c55d7a14b5c3221f',
    messagingSenderId: '665514511694',
    projectId: 'test-6689e',
    authDomain: 'test-6689e.firebaseapp.com',
    storageBucket: 'test-6689e.firebasestorage.app',
    measurementId: 'G-VPBSNMBGH2',
  );
}
